# Generated by Django 5.2.3 on 2025-07-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_classchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classchange',
            name='approved_by',
            field=models.CharField(choices=[('Nuwan', 'Nuwan Jayaneththi'), ('Rasika', 'Rasika Perera'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='classchange',
            name='center',
            field=models.CharField(max_length=100, verbose_name='Center'),
        ),
        migrations.AlterField(
            model_name='classchange',
            name='previous_class',
            field=models.CharField(choices=[('Motor Cycle', 'Motor Cycle'), ('Motor Car', 'Motor Car'), ('Tricycle', 'Tricycle'), ('Dual Purpose', 'Dual Purpose'), ('Motor Lorry', 'Motor Lorry'), ('Motor Coach', 'Motor Coach'), ('Prime Mover', 'Prime Mover'), ('Land Vehicle', 'Land Vehicle'), ('Omni Bus', 'Omni Bus')], max_length=100),
        ),
        migrations.AlterField(
            model_name='classchange',
            name='refund',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='classchange',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classchange',
            name='vin',
            field=models.CharField(max_length=100, verbose_name='Vehicle Identification Number'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='tele_no',
            field=models.CharField(max_length=20, verbose_name='Customer Mobile Number'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='vin',
            field=models.CharField(max_length=100, verbose_name='Vehicle Identification Number'),
        ),
    ]
